// ─── Trainer chat (Jack) — shared UI strings ─────────────────────────────────
// All actual replies are generated by Gemini via the Cloudflare Worker (see
// constants/trainerAI.js). This file only holds the static greeting and the
// quick-question chips shown in the chat UI — it no longer produces answers.

export const TRAINER_NAME = "Jack";

export const TRAINER_GREETING =
  "Hi, I am Jack, your personal trainer 💪\n\nAsk me anything about workouts or diet — I will assist you!";

// Shown as tappable chips before the first user message.
export const QUICK_QUESTIONS = [
  "How do I lose belly fat?",
  "What is a calorie deficit?",
  "How much protein do I need?",
  "Best egg recipes for muscle?",
  "How much sleep do I need?",
  "What should I eat after a workout?",
];
