const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  withMainActivity,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const { BUCKETS, EXPRESSIONS, tightenEmoji } = require("../constants/widgetData");

// ─── Push Daily home-screen widget ───────────────────────────────────────────
// android/ is gitignored and regenerated by `expo prebuild`, so the widget has
// to be written by a plugin or it disappears on every rebuild. Same reason
// withProguardRules.js exists.
//
// The widget shows Jack (12 expressions), the user's first name, their streak
// and one short line, then opens the app when tapped.
//
// DATA BRIDGE — Android gives JS no way to push to a widget without a custom
// native module, so instead the app writes a small JSON file into its own
// files dir (see constants/widgetPromo.js#syncWidget) and the widget reads it
// at render time. expo-file-system's documentDirectory IS context.filesDir on
// Android, so both sides agree on the path with no configuration.
//
// updatePeriodMillis alone would leave the widget up to 30 minutes stale (30
// min is Android's hard floor), which is very visible right after a workout —
// the whole point is that finishing a session changes what Jack says. JS
// cannot broadcast to a widget without a native module, so instead
// MainActivity re-renders every widget in onPause. The user only ever sees
// the home screen AFTER leaving the app, so by the time the widget is on
// screen it has already been refreshed.
//
// Nothing here is private: a home screen is visible to anyone nearby, so the
// bridge carries a first name and a workout count and nothing else.

const PKG = "com.pushdaily.homeworkout.fit";
const BRIDGE_FILE = "push_daily_widget.json";

// Handled in app/_layout.tsx: expo-router routes /home, then the ?tab= param
// selects the bottom tab. Must stay in step with the tab's registered name.
const DEEP_LINK = "pushdaily://home?tab=Workouts";

const kstr = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;

// Buckets are baked in from constants/widgetData.js so JS and Kotlin cannot
// disagree about the copy.
// tightenEmoji is applied HERE rather than in Kotlin: the non-breaking space is
// baked into the string literal, so the widget needs no emoji detection of its
// own (Android's regex engine has no reliable \p{Extended_Pictographic}).
const BUCKET_KT = BUCKETS.map(
  (b) =>
    `            Bucket(${kstr(b.id)}, ${kstr(EXPRESSIONS[b.expression])}, arrayOf(${b.lines
      .map((l) => kstr(tightenEmoji(l)))
      .join(", ")}))`,
).join(",\n");

const WIDGET_KT = `package ${PKG}

import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.util.TypedValue
import android.view.View
import android.widget.RemoteViews
import org.json.JSONObject
import java.io.File
import java.util.Calendar
import java.util.TimeZone

/**
 * Home-screen widget: Jack, a short line, and the user's streak.
 *
 * Bucket selection mirrors pickBucket() in constants/widgetData.js exactly.
 * If either side changes, change both — the copy itself is generated from that
 * file, but this rule ladder is hand-mirrored.
 */
class PushDailyWidget : AppWidgetProvider() {

    private data class Bucket(val id: String, val drawable: String, val lines: Array<String>)

    companion object {

        private val BUCKETS = arrayOf(
${BUCKET_KT}
        )

        private fun bucket(id: String) = BUCKETS.first { it.id == id }

        /** Reads the JSON the app writes. Absent on a fresh install — that is
         *  a normal state, not an error, so it falls back to empty defaults. */
        private fun readState(context: Context): JSONObject {
            return try {
                val f = File(context.filesDir, ${kstr(BRIDGE_FILE)})
                if (f.exists()) JSONObject(f.readText()) else JSONObject()
            } catch (e: Exception) {
                JSONObject()
            }
        }

        private fun pick(
            hour: Int,
            streak: Int,
            trainedToday: Boolean,
            everTrained: Boolean,
            daysSinceLast: Int
        ): Bucket {
            if (trainedToday) return bucket("done_today")
            if (!everTrained) return bucket("welcome")
            // Genuinely lapsed, not merely resting — see widgetData.js.
            if (daysSinceLast >= 3) return bucket("comeback")
            // Morning greeting outranks streak copy: point at today, not
            // yesterday.
            if (hour < 10) return bucket("morning")
            if (streak > 0 && hour >= 19) return bucket("streak_danger")
            // Any live streak carries through the day.
            if (streak > 0) return bucket("streak_proud")
            if (hour < 12) return bucket("midmorning")
            if (hour < 15) return bucket("afternoon")
            if (hour < 17) return bucket("late_afternoon")
            if (hour < 19) return bucket("prime_time")
            if (hour < 22) return bucket("evening")
            return bucket("night")
        }

        /**
         * Days since the local epoch. Must match localEpochDay() in
         * constants/widgetPromo.js — both shift UTC by the zone offset and
         * floor, so they agree on which calendar day it is.
         */
        private fun todayEpochDay(): Int {
            val now = System.currentTimeMillis()
            val offset = TimeZone.getDefault().getOffset(now)
            return Math.floorDiv(now + offset, 86400000L).toInt()
        }

        private fun firstName(raw: String): String {
            val trimmed = raw.trim()
            if (trimmed.isEmpty()) return "champ"
            return trimmed.split(" ").first()
        }

        fun render(context: Context, manager: AppWidgetManager, widgetId: Int) {
            val state = readState(context)
            val name = firstName(state.optString("name", ""))

            // Everything date-relative is derived HERE, against the clock at
            // render time — never read as a stored boolean. The bridge file can
            // be days old, so "did they train today" has to be recomputed or
            // the widget congratulates people for yesterday's session forever.
            val lastWorkoutDay =
                if (state.isNull("lastWorkoutDay")) -1 else state.optInt("lastWorkoutDay", -1)

            val everTrained = lastWorkoutDay >= 0
            val daysSinceLast = if (everTrained) todayEpochDay() - lastWorkoutDay else -1
            val trainedToday = everTrained && daysSinceLast == 0

            // getCurrentStreak() in JS only counts a streak that includes today
            // or yesterday, so once the gap reaches two days the stored number
            // is stale and the streak is over.
            val streak = if (daysSinceLast in 0..1) state.optInt("streak", 0) else 0

            val cal = Calendar.getInstance()
            val hour = cal.get(Calendar.HOUR_OF_DAY)
            val b = pick(hour, streak, trainedToday, everTrained, daysSinceLast)

            // Day-of-year rotation: the line changes daily instead of flicking
            // to a new one on every half-hourly refresh.
            val line = b.lines[Math.floorMod(cal.get(Calendar.DAY_OF_YEAR), b.lines.size)]

            // Mirrors format() in constants/widgetData.js.
            val text = line
                .replace("{name}", name)
                .replace("{streak}", streak.toString())
                .replace("{days}", if (streak == 1) "1 day" else streak.toString() + " days")
                .replace("{next}", (streak + 1).toString())

            val views = RemoteViews(context.packageName, R.layout.push_daily_widget)
            views.setTextViewText(R.id.widget_message, text)

            val drawableId = context.resources.getIdentifier(
                b.drawable, "drawable", context.packageName
            )
            if (drawableId != 0) {
                views.setImageViewResource(R.id.widget_character, drawableId)
            }

            // The streak is the headline when there is one. With no streak the
            // row would leave an empty band above the character, so the message
            // grows to fill the space instead of floating in it.
            if (streak > 0) {
                views.setViewVisibility(R.id.widget_streak, View.VISIBLE)
                views.setTextViewText(R.id.widget_streak_count, streak.toString())
                views.setTextViewTextSize(R.id.widget_message, TypedValue.COMPLEX_UNIT_SP, 11f)
            } else {
                views.setViewVisibility(R.id.widget_streak, View.GONE)
                views.setTextViewTextSize(R.id.widget_message, TypedValue.COMPLEX_UNIT_SP, 15f)
            }

            // Whole widget is the tap target. Deep-links straight to the
            // Workouts tab rather than the default launch route — someone
            // tapping a nudge to train should land on the workouts, not wherever
            // the app happened to be. setPackage keeps the intent internal.
            val launch = Intent(Intent.ACTION_VIEW, Uri.parse(${kstr(DEEP_LINK)})).apply {
                setPackage(context.packageName)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
            }

            val flags = PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
            val pending = PendingIntent.getActivity(context, 0, launch, flags)
            views.setOnClickPendingIntent(R.id.widget_root, pending)

            manager.updateAppWidget(widgetId, views)
        }

        /** Re-renders every placed widget. Called on APPWIDGET_UPDATE. */
        fun renderAll(context: Context) {
            val manager = AppWidgetManager.getInstance(context)
            val ids = manager.getAppWidgetIds(
                android.content.ComponentName(context, PushDailyWidget::class.java)
            )
            ids.forEach { render(context, manager, it) }
        }
    }

    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        appWidgetIds.forEach { render(context, appWidgetManager, it) }
    }
}
`;

// Square 2x2, laid out like the Duolingo widget: the streak is the hero at the
// top-left, the line sits under it, and the character fills the bottom and
// bleeds off the edge.
//
// Background is the accent yellow the art was drawn on. Measured contrast
// decided this: on brand orange the mascot's own orange body scores 1.22 and
// disappears, and on a dark background its dark outline drops to ~1.2 and the
// silhouette falls apart. On #FFD23F both the outline and the dark text score
// 8.78, well past WCAG AA, and the character reads exactly as designed.
const LAYOUT_XML = `<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/widget_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/widget_background">

    <!-- Negative bottom margin lets the feet crop against the widget edge, the
         way Duo does. FrameLayout clips children, so nothing escapes. -->
    <ImageView
        android:id="@+id/widget_character"
        android:layout_width="match_parent"
        android:layout_height="104dp"
        android:layout_gravity="bottom|center_horizontal"
        android:layout_marginBottom="-10dp"
        android:scaleType="fitCenter"
        android:src="@drawable/mascot_hi"
        android:contentDescription="Push Daily trainer" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="top|start"
        android:orientation="vertical"
        android:paddingStart="13dp"
        android:paddingEnd="13dp"
        android:paddingTop="11dp">

        <!-- Hidden by the provider when there is no streak to show. -->
        <LinearLayout
            android:id="@+id/widget_streak"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:gravity="center_vertical"
            android:visibility="gone">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="🔥"
                android:textSize="19sp" />

            <TextView
                android:id="@+id/widget_streak_count"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="5dp"
                android:textColor="#2D3436"
                android:textSize="26sp"
                android:textStyle="bold"
                android:includeFontPadding="false" />
        </LinearLayout>

        <TextView
            android:id="@+id/widget_message"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="3dp"
            android:maxLines="2"
            android:ellipsize="end"
            android:textColor="#2D3436"
            android:textSize="11sp"
            android:textStyle="bold"
            android:lineSpacingExtra="1dp" />
    </LinearLayout>
</FrameLayout>
`;

// colors.accent — and the colour the character art was drawn on, so the
// outline keeps the contrast it was designed with. See LAYOUT_XML.
const BACKGROUND_XML = `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="#FFD23F" />
    <corners android:radius="20dp" />
</shape>
`;

// updatePeriodMillis has a 30-minute floor enforced by Android; anything
// smaller is silently clamped, so state it honestly.
//
// targetCell*/previewLayout are API 31+ only. previewImage is the fallback so
// the widget still shows something in the picker on Android 7-11 (minSdk 24).
// 2x2 square. On the usual 4-column launcher grid that is half the screen
// width. Android's sizing formula is 70*cells - 30, hence 110dp.
const PROVIDER_INFO_XML = `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="110dp"
    android:minHeight="110dp"
    android:targetCellWidth="2"
    android:targetCellHeight="2"
    android:updatePeriodMillis="1800000"
    android:initialLayout="@layout/push_daily_widget"
    android:previewLayout="@layout/push_daily_widget"
    android:previewImage="@mipmap/ic_launcher"
    android:resizeMode="horizontal|vertical"
    android:widgetCategory="home_screen"
    android:description="@string/widget_description" />
`;

const writeFile = (filePath, contents) => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents, "utf8");
};

/** Drops the Kotlin + XML + character art into the generated Android project. */
const withWidgetFiles = (config) =>
  withDangerousMod(config, [
    "android",
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const res = path.join(root, "app", "src", "main", "res");

      writeFile(
        path.join(root, "app", "src", "main", "java", ...PKG.split("."), "PushDailyWidget.kt"),
        WIDGET_KT,
      );
      writeFile(path.join(res, "layout", "push_daily_widget.xml"), LAYOUT_XML);
      writeFile(path.join(res, "drawable", "widget_background.xml"), BACKGROUND_XML);
      writeFile(path.join(res, "xml", "push_daily_widget_info.xml"), PROVIDER_INFO_XML);

      // Jack's expressions. drawable-nodpi because these are already sized for
      // the 62dp slot — letting Android density-scale them would only blur
      // them and multiply the APK cost across four buckets.
      const artSrc = path.join(cfg.modRequest.projectRoot, "assets", "widget");
      const artDest = path.join(res, "drawable-nodpi");
      fs.mkdirSync(artDest, { recursive: true });

      // Drop character art from a previous set. prebuild never deletes, so
      // without this an old mascot stays in res/ forever — bloating the APK
      // and, worse, still resolving via getIdentifier() if a name is reused.
      const keep = new Set(Object.values(EXPRESSIONS).map((d) => `${d}.png`));
      for (const file of fs.readdirSync(artDest)) {
        if (/^(mascot|jack)_.*\.png$/.test(file) && !keep.has(file)) {
          fs.unlinkSync(path.join(artDest, file));
        }
      }

      for (const drawable of Object.values(EXPRESSIONS)) {
        const from = path.join(artSrc, `${drawable}.png`);
        if (!fs.existsSync(from)) {
          throw new Error(
            `[withWidget] missing character art: assets/widget/${drawable}.png — ` +
              `the layout references it, so the build would fail later and less clearly.`,
          );
        }
        fs.copyFileSync(from, path.join(artDest, `${drawable}.png`));
      }

      // The provider description is referenced by name, so it must exist.
      const stringsPath = path.join(res, "values", "strings.xml");
      if (fs.existsSync(stringsPath)) {
        let strings = fs.readFileSync(stringsPath, "utf8");
        if (!strings.includes("widget_description")) {
          strings = strings.replace(
            "</resources>",
            `  <string name="widget_description">Daily nudge to train</string>\n</resources>`,
          );
          fs.writeFileSync(stringsPath, strings, "utf8");
        }
      }

      return cfg;
    },
  ]);

/** Registers the provider + its APPWIDGET_UPDATE receiver in the manifest. */
const withWidgetManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.receiver = app.receiver || [];

    const name = `.PushDailyWidget`;
    if (app.receiver.some((r) => r.$?.["android:name"] === name)) return cfg;

    app.receiver.push({
      $: { "android:name": name, "android:exported": "false" },
      "intent-filter": [
        {
          action: [
            { $: { "android:name": "android.appwidget.action.APPWIDGET_UPDATE" } },
          ],
        },
      ],
      "meta-data": [
        {
          $: {
            "android:name": "android.appwidget.provider",
            "android:resource": "@xml/push_daily_widget_info",
          },
        },
      ],
    });

    return cfg;
  });

/**
 * Re-renders every placed widget when the app goes to the background.
 *
 * This is what makes a finished workout show up immediately: JS has already
 * written the bridge file by then, and the user cannot see their home screen
 * until they leave the app — which is exactly when onPause fires. Without it
 * they would wait out Android's 30-minute update floor.
 */
const withWidgetRefreshOnPause = (config) =>
  withMainActivity(config, (cfg) => {
    const marker = "PushDailyWidget.renderAll";
    if (cfg.modResults.contents.includes(marker)) return cfg;

    if (cfg.modResults.language !== "kt") {
      throw new Error(
        `[withWidget] expected a Kotlin MainActivity, got "${cfg.modResults.language}" — ` +
          `the refresh hook below is Kotlin and would not compile.`,
      );
    }

    const hook = `
  override fun onPause() {
    super.onPause()
    // Refresh the home-screen widget on the way out; see plugins/withWidget.js.
    PushDailyWidget.renderAll(this)
  }

  override fun getMainComponentName(): String`;

    const anchor = "\n  override fun getMainComponentName(): String";
    if (!cfg.modResults.contents.includes(anchor)) {
      throw new Error(
        "[withWidget] could not find getMainComponentName() in MainActivity — " +
          "the generated template changed, so the widget refresh hook was not installed.",
      );
    }

    cfg.modResults.contents = cfg.modResults.contents.replace(anchor, `\n${hook}`);
    return cfg;
  });

module.exports = (config) =>
  withWidgetRefreshOnPause(withWidgetManifest(withWidgetFiles(config)));
