const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  withMainActivity,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const { BUCKETS, EXPRESSIONS } = require("../constants/widgetData");

// ─── Push Daily home-screen widget ───────────────────────────────────────────
// android/ is gitignored and regenerated by `expo prebuild`, so the widget has
// to be written by a plugin or it disappears on every rebuild. Same reason
// withProguardRules.js exists.
//
// The widget shows Jack (12 expressions), the user's first name, their streak
// and one short line, then opens the app when tapped.
//
// DATA BRIDGE — Android gives JS no way to push to a widget without a custom
// native module, so instead the app writes a small JSON file into its own
// files dir (see constants/widgetPromo.js#syncWidget) and the widget reads it
// at render time. expo-file-system's documentDirectory IS context.filesDir on
// Android, so both sides agree on the path with no configuration.
//
// updatePeriodMillis alone would leave the widget up to 30 minutes stale (30
// min is Android's hard floor), which is very visible right after a workout —
// the whole point is that finishing a session changes what Jack says. JS
// cannot broadcast to a widget without a native module, so instead
// MainActivity re-renders every widget in onPause. The user only ever sees
// the home screen AFTER leaving the app, so by the time the widget is on
// screen it has already been refreshed.
//
// Nothing here is private: a home screen is visible to anyone nearby, so the
// bridge carries a first name and a workout count and nothing else.

const PKG = "com.pushdaily.homeworkout.fit";
const PRIMARY = "#FF6B35";
const BRIDGE_FILE = "push_daily_widget.json";

// Handled in app/_layout.tsx: expo-router routes /home, then the ?tab= param
// selects the bottom tab. Must stay in step with the tab's registered name.
const DEEP_LINK = "pushdaily://home?tab=Workouts";

const kstr = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;

// Buckets are baked in from constants/widgetData.js so JS and Kotlin cannot
// disagree about the copy.
const BUCKET_KT = BUCKETS.map(
  (b) =>
    `            Bucket(${kstr(b.id)}, ${kstr(EXPRESSIONS[b.expression])}, arrayOf(${b.lines
      .map(kstr)
      .join(", ")}))`,
).join(",\n");

const WIDGET_KT = `package ${PKG}

import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.view.View
import android.widget.RemoteViews
import org.json.JSONObject
import java.io.File
import java.util.Calendar

/**
 * Home-screen widget: Jack, a short line, and the user's streak.
 *
 * Bucket selection mirrors pickBucket() in constants/widgetData.js exactly.
 * If either side changes, change both — the copy itself is generated from that
 * file, but this rule ladder is hand-mirrored.
 */
class PushDailyWidget : AppWidgetProvider() {

    private data class Bucket(val id: String, val drawable: String, val lines: Array<String>)

    companion object {

        private val BUCKETS = arrayOf(
${BUCKET_KT}
        )

        private fun bucket(id: String) = BUCKETS.first { it.id == id }

        /** Reads the JSON the app writes. Absent on a fresh install — that is
         *  a normal state, not an error, so it falls back to empty defaults. */
        private fun readState(context: Context): JSONObject {
            return try {
                val f = File(context.filesDir, ${kstr(BRIDGE_FILE)})
                if (f.exists()) JSONObject(f.readText()) else JSONObject()
            } catch (e: Exception) {
                JSONObject()
            }
        }

        private fun pick(
            hour: Int,
            streak: Int,
            trainedToday: Boolean,
            everTrained: Boolean,
            daysSinceLast: Int
        ): Bucket {
            if (trainedToday) return bucket("done_today")
            if (!everTrained) return bucket("welcome")
            // Genuinely lapsed, not merely resting — see widgetData.js.
            if (daysSinceLast >= 3) return bucket("comeback")
            if (streak > 0 && hour >= 19) return bucket("streak_danger")
            // Mid-streak users get celebrated, not needled.
            if (streak >= 3 && hour >= 12 && hour < 19) return bucket("streak_proud")
            if (hour < 10) return bucket("morning")
            if (hour < 12) return bucket("midmorning")
            if (hour < 15) return bucket("afternoon")
            if (hour < 17) return bucket("late_afternoon")
            if (hour < 19) return bucket("prime_time")
            if (hour < 22) return bucket("evening")
            return bucket("night")
        }

        private fun firstName(raw: String): String {
            val trimmed = raw.trim()
            if (trimmed.isEmpty()) return "champ"
            return trimmed.split(" ").first()
        }

        fun render(context: Context, manager: AppWidgetManager, widgetId: Int) {
            val state = readState(context)
            val name = firstName(state.optString("name", ""))
            val streak = state.optInt("streak", 0)
            val trainedToday = state.optBoolean("trainedToday", false)
            val everTrained = state.optBoolean("everTrained", false)
            val daysSinceLast = state.optInt("daysSinceLast", -1)

            val cal = Calendar.getInstance()
            val hour = cal.get(Calendar.HOUR_OF_DAY)
            val b = pick(hour, streak, trainedToday, everTrained, daysSinceLast)

            // Day-of-year rotation: the line changes daily instead of flicking
            // to a new one on every half-hourly refresh.
            val line = b.lines[Math.floorMod(cal.get(Calendar.DAY_OF_YEAR), b.lines.size)]
            val text = line.replace("{name}", name).replace("{streak}", streak.toString())

            val views = RemoteViews(context.packageName, R.layout.push_daily_widget)
            views.setTextViewText(R.id.widget_message, text)

            val drawableId = context.resources.getIdentifier(
                b.drawable, "drawable", context.packageName
            )
            if (drawableId != 0) {
                views.setImageViewResource(R.id.widget_character, drawableId)
            }

            // Streak pill only earns its space once there is a streak to show.
            if (streak > 0) {
                views.setViewVisibility(R.id.widget_streak, View.VISIBLE)
                views.setTextViewText(R.id.widget_streak_count, streak.toString())
            } else {
                views.setViewVisibility(R.id.widget_streak, View.GONE)
            }

            // Whole widget is the tap target. Deep-links straight to the
            // Workouts tab rather than the default launch route — someone
            // tapping a nudge to train should land on the workouts, not wherever
            // the app happened to be. setPackage keeps the intent internal.
            val launch = Intent(Intent.ACTION_VIEW, Uri.parse(${kstr(DEEP_LINK)})).apply {
                setPackage(context.packageName)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
            }

            val flags = PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
            val pending = PendingIntent.getActivity(context, 0, launch, flags)
            views.setOnClickPendingIntent(R.id.widget_root, pending)

            manager.updateAppWidget(widgetId, views)
        }

        /** Re-renders every placed widget. Called on APPWIDGET_UPDATE. */
        fun renderAll(context: Context) {
            val manager = AppWidgetManager.getInstance(context)
            val ids = manager.getAppWidgetIds(
                android.content.ComponentName(context, PushDailyWidget::class.java)
            )
            ids.forEach { render(context, manager, it) }
        }
    }

    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray
    ) {
        appWidgetIds.forEach { render(context, appWidgetManager, it) }
    }
}
`;

// Square 2x2. Jack takes every pixel of height the message does not need, so
// the character reads at a glance and the card stays uncluttered — no brand
// row, because at this size Jack IS the brand mark.
const LAYOUT_XML = `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/widget_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="10dp"
    android:background="@drawable/widget_background">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">

        <ImageView
            android:id="@+id/widget_character"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="fitCenter"
            android:src="@drawable/jack_encouraging"
            android:contentDescription="Push Daily trainer" />

        <!-- Floats over the art so it costs no height. Hidden by the provider
             when the streak is 0. -->
        <LinearLayout
            android:id="@+id/widget_streak"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="top|end"
            android:orientation="horizontal"
            android:gravity="center_vertical"
            android:paddingStart="7dp"
            android:paddingEnd="8dp"
            android:paddingTop="2dp"
            android:paddingBottom="2dp"
            android:visibility="gone"
            android:background="@drawable/widget_streak_pill">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="🔥"
                android:textSize="10sp" />

            <TextView
                android:id="@+id/widget_streak_count"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="3dp"
                android:textColor="#C2410C"
                android:textSize="11sp"
                android:textStyle="bold" />
        </LinearLayout>
    </FrameLayout>

    <TextView
        android:id="@+id/widget_message"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="6dp"
        android:gravity="center_horizontal"
        android:maxLines="2"
        android:ellipsize="end"
        android:textColor="#111827"
        android:textSize="12sp"
        android:textStyle="bold"
        android:lineSpacingExtra="1dp" />
</LinearLayout>
`;

const BACKGROUND_XML = `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="#FFFFFF" />
    <corners android:radius="20dp" />
</shape>
`;

const STREAK_PILL_XML = `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <solid android:color="#FFEDD5" />
    <corners android:radius="999dp" />
</shape>
`;

// updatePeriodMillis has a 30-minute floor enforced by Android; anything
// smaller is silently clamped, so state it honestly.
//
// targetCell*/previewLayout are API 31+ only. previewImage is the fallback so
// the widget still shows something in the picker on Android 7-11 (minSdk 24).
// 2x2 square. On the usual 4-column launcher grid that is half the screen
// width. Android's sizing formula is 70*cells - 30, hence 110dp.
const PROVIDER_INFO_XML = `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="110dp"
    android:minHeight="110dp"
    android:targetCellWidth="2"
    android:targetCellHeight="2"
    android:updatePeriodMillis="1800000"
    android:initialLayout="@layout/push_daily_widget"
    android:previewLayout="@layout/push_daily_widget"
    android:previewImage="@mipmap/ic_launcher"
    android:resizeMode="horizontal|vertical"
    android:widgetCategory="home_screen"
    android:description="@string/widget_description" />
`;

const writeFile = (filePath, contents) => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents, "utf8");
};

/** Drops the Kotlin + XML + character art into the generated Android project. */
const withWidgetFiles = (config) =>
  withDangerousMod(config, [
    "android",
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const res = path.join(root, "app", "src", "main", "res");

      writeFile(
        path.join(root, "app", "src", "main", "java", ...PKG.split("."), "PushDailyWidget.kt"),
        WIDGET_KT,
      );
      writeFile(path.join(res, "layout", "push_daily_widget.xml"), LAYOUT_XML);
      writeFile(path.join(res, "drawable", "widget_background.xml"), BACKGROUND_XML);
      writeFile(path.join(res, "drawable", "widget_streak_pill.xml"), STREAK_PILL_XML);
      writeFile(path.join(res, "xml", "push_daily_widget_info.xml"), PROVIDER_INFO_XML);

      // Jack's expressions. drawable-nodpi because these are already sized for
      // the 62dp slot — letting Android density-scale them would only blur
      // them and multiply the APK cost across four buckets.
      const artSrc = path.join(cfg.modRequest.projectRoot, "assets", "widget");
      const artDest = path.join(res, "drawable-nodpi");
      fs.mkdirSync(artDest, { recursive: true });

      for (const drawable of Object.values(EXPRESSIONS)) {
        const from = path.join(artSrc, `${drawable}.png`);
        if (!fs.existsSync(from)) {
          throw new Error(
            `[withWidget] missing character art: assets/widget/${drawable}.png — ` +
              `the layout references it, so the build would fail later and less clearly.`,
          );
        }
        fs.copyFileSync(from, path.join(artDest, `${drawable}.png`));
      }

      // The provider description is referenced by name, so it must exist.
      const stringsPath = path.join(res, "values", "strings.xml");
      if (fs.existsSync(stringsPath)) {
        let strings = fs.readFileSync(stringsPath, "utf8");
        if (!strings.includes("widget_description")) {
          strings = strings.replace(
            "</resources>",
            `  <string name="widget_description">Daily nudge to train</string>\n</resources>`,
          );
          fs.writeFileSync(stringsPath, strings, "utf8");
        }
      }

      return cfg;
    },
  ]);

/** Registers the provider + its APPWIDGET_UPDATE receiver in the manifest. */
const withWidgetManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.receiver = app.receiver || [];

    const name = `.PushDailyWidget`;
    if (app.receiver.some((r) => r.$?.["android:name"] === name)) return cfg;

    app.receiver.push({
      $: { "android:name": name, "android:exported": "false" },
      "intent-filter": [
        {
          action: [
            { $: { "android:name": "android.appwidget.action.APPWIDGET_UPDATE" } },
          ],
        },
      ],
      "meta-data": [
        {
          $: {
            "android:name": "android.appwidget.provider",
            "android:resource": "@xml/push_daily_widget_info",
          },
        },
      ],
    });

    return cfg;
  });

/**
 * Re-renders every placed widget when the app goes to the background.
 *
 * This is what makes a finished workout show up immediately: JS has already
 * written the bridge file by then, and the user cannot see their home screen
 * until they leave the app — which is exactly when onPause fires. Without it
 * they would wait out Android's 30-minute update floor.
 */
const withWidgetRefreshOnPause = (config) =>
  withMainActivity(config, (cfg) => {
    const marker = "PushDailyWidget.renderAll";
    if (cfg.modResults.contents.includes(marker)) return cfg;

    if (cfg.modResults.language !== "kt") {
      throw new Error(
        `[withWidget] expected a Kotlin MainActivity, got "${cfg.modResults.language}" — ` +
          `the refresh hook below is Kotlin and would not compile.`,
      );
    }

    const hook = `
  override fun onPause() {
    super.onPause()
    // Refresh the home-screen widget on the way out; see plugins/withWidget.js.
    PushDailyWidget.renderAll(this)
  }

  override fun getMainComponentName(): String`;

    const anchor = "\n  override fun getMainComponentName(): String";
    if (!cfg.modResults.contents.includes(anchor)) {
      throw new Error(
        "[withWidget] could not find getMainComponentName() in MainActivity — " +
          "the generated template changed, so the widget refresh hook was not installed.",
      );
    }

    cfg.modResults.contents = cfg.modResults.contents.replace(anchor, `\n${hook}`);
    return cfg;
  });

module.exports = (config) =>
  withWidgetRefreshOnPause(withWidgetManifest(withWidgetFiles(config)));
